services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: c_ide
    ports:
      - "5434:5432"
    volumes:
      - c_ide_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6380:6379"

volumes:
  c_ide_postgres_data: